name: Deploy to Cloudflare Pages

on:
  push:
    branches:
      - main

permissions:
  contents: read
  deployments: write

jobs:
  deploy:
    name: Deploy Pawtraits
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Deploy to Cloudflare Pages
        uses: cloudflare/wrangler-action@v4
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: 267721fba0c2f528c6ef615493068e5a
          command: pages deploy . --project-name=pawtraitsforapound-site --branch=main
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
